export { default as DocumentEditorModal } from './DocumentEditorModal'
export { default as DocumentEditorToolbar } from './DocumentEditorToolbar'
export { default as DocumentRails } from './DocumentRails'
export { default as TipTapEditor } from './TipTapEditor'
export { default as VersionHistoryPanel } from './VersionHistoryPanel'
export { default as VersionDiff } from './VersionDiff'
export { default as VersionControls } from './VersionControls'

// Re-export types
export type { DocumentEditorModalProps } from './DocumentEditorModal'
export type { DocumentEditorToolbarProps, Editor } from './DocumentEditorToolbar'
export type { DocumentRailsProps, RailConnection } from './DocumentRails'
export type { TipTapEditorProps } from './TipTapEditor'
export type { VersionHistoryPanelProps } from './VersionHistoryPanel'
export type { VersionDiffProps } from './VersionDiff'
export type { VersionControlsProps } from './VersionControls'